In [1]:
import numpy as np

### Data Types and Attribuites 

In [3]:
ar1=np.array([1,2,5,4])

In [4]:
ar1

array([1, 2, 5, 4])

In [5]:
type(ar1)

numpy.ndarray

In [21]:
ar2=np.array([[1,2,5.6,4],[2.3,5,7.7,8]])
ar3=np.array([[[1,8,3,5],[5,5,7,1]],[[2,5,8,7],[9,2,1,5]]] )


In [13]:
ar2

array([[1. , 2. , 5.6, 4. ],
       [2.3, 5. , 7.7, 8. ]])

In [23]:
ar3

array([[[1, 8, 3, 5],
        [5, 5, 7, 1]],

       [[2, 5, 8, 7],
        [9, 2, 1, 5]]])

In [22]:
ar3.shape

(2, 2, 4)

In [17]:
ar3.ndim

3

In [24]:
ar3.size

16

In [25]:
type(ar3)

numpy.ndarray

In [26]:
ar3.dtype

dtype('int32')

In [28]:
import pandas as pd

In [33]:
 a2_df=pd.DataFrame(ar2)

In [34]:
a2_df

0    1    2    3
0  1.0  2.0  5.6  4.0
1  2.3  5.0  7.7  8.0

### Create Arrays

In [35]:
s_r=np.array([1,2,3])

In [36]:
s_r

array([1, 2, 3])

In [38]:
ones = np.ones((2,3))

In [39]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
zeros=np.zeros((2,3))

In [46]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
arr=np.arange(0,10,2)

In [49]:
arr

array([0, 2, 4, 6, 8])

In [69]:
random_arr=np.random.randint(0,10,size=(2,5))

In [70]:
random_arr

array([[9, 2, 2, 6, 8],
       [9, 3, 4, 5, 5]])

In [54]:
random_arr2=np.random.rand(3,3)

In [55]:
random_arr2

array([[0.22796389, 0.10890352, 0.64928421],
       [0.92807258, 0.10810472, 0.60516184],
       [0.17067863, 0.34654011, 0.15457701]])

In [68]:
np.random.seed(8)
random_arr2=np.random.rand(3,3)
random_arr2

array([[0.8734294 , 0.96854066, 0.86919454],
       [0.53085569, 0.23272833, 0.0113988 ],
       [0.43046882, 0.40235136, 0.52267467]])

### Viewing Array and matrices 

In [73]:
random_arr


array([[9, 2, 2, 6, 8],
       [9, 3, 4, 5, 5]])

In [74]:
np.unique(random_arr)

array([2, 3, 4, 5, 6, 8, 9])

In [79]:
random_r2=np.random.randint(0,10,size=(2,3,4,5))

In [80]:
random_r2

array([[[[9, 6, 4, 5, 2],
         [2, 6, 6, 6, 7],
         [9, 6, 0, 9, 2],
         [7, 9, 2, 6, 3]],

        [[0, 9, 0, 0, 6],
         [9, 7, 4, 7, 9],
         [4, 8, 2, 7, 2],
         [8, 6, 5, 2, 3]],

        [[3, 8, 7, 9, 7],
         [3, 8, 0, 7, 3],
         [0, 9, 0, 1, 2],
         [6, 7, 3, 8, 2]]],


       [[[9, 6, 5, 1, 3],
         [0, 0, 8, 6, 7],
         [8, 1, 0, 8, 9],
         [5, 2, 2, 2, 7]],

        [[7, 7, 6, 0, 3],
         [2, 4, 1, 5, 6],
         [3, 3, 0, 4, 6],
         [8, 4, 6, 9, 8]],

        [[5, 0, 2, 3, 5],
         [3, 9, 6, 9, 2],
         [6, 1, 1, 9, 3],
         [0, 2, 8, 0, 1]]]])

In [82]:
random_r2[:,:2,:1,:]

array([[[[9, 6, 4, 5, 2]],

        [[0, 9, 0, 0, 6]]],


       [[[9, 6, 5, 1, 3]],

        [[7, 7, 6, 0, 3]]]])

### Man and Create Arrays 

### Arithmetics


In [83]:
ar1*ar2

array([[ 1. ,  4. , 28. , 16. ],
       [ 2.3, 10. , 38.5, 32. ]])

### Agr

In [84]:
np.sum(ar2)

35.6

In [85]:
%timeit

In [88]:
ar2.shape

(2, 4)

In [90]:
ar2.reshape(2,4,1)

array([[[1. ],
        [2. ],
        [5.6],
        [4. ]],

       [[2.3],
        [5. ],
        [7.7],
        [8. ]]])

In [91]:
ar2.T

array([[1. , 2.3],
       [2. , 5. ],
       [5.6, 7.7],
       [4. , 8. ]])

In [95]:
sales=np.random.randint(20,size=(5,3))
sales

array([[12, 19,  2],
       [ 7, 12,  1],
       [ 1,  6,  8],
       [12,  0,  4],
       [ 8, 17,  0]])

In [98]:
weekly_sales=pd.DataFrame(sales,index=["Mon","Tue","Wed","Thur","Fri"],columns=["Almond","Peanut","Cachew"])

In [99]:
weekly_sales

Almond  Peanut  Cachew
Mon       12      19       2
Tue        7      12       1
Wed        1       6       8
Thur      12       0       4
Fri        8      17       0

In [100]:
prices=np.array([10,8,12])

In [101]:
prices

array([10,  8, 12])

In [105]:
B_Price=pd.DataFrame(prices.reshape(1,3),index=["Price"],columns=["Almond","Peanut","Cachew"])

In [106]:
B_Price

Almond  Peanut  Cachew
Price      10       8      12

In [124]:
total=B_Price.dot(weekly_sales.T)

In [125]:
total

Mon  Tue  Wed  Thur  Fri
Price  296  178  154   168  216

In [123]:
weekly_sales.drop(["Total ($)"],axis=1,inplace=True)

In [122]:
weekly_sales

Almond  Peanut  Cachew  Total ($)
Mon       12      19       2        296
Tue        7      12       1        178
Wed        1       6       8        154
Thur      12       0       4        168
Fri        8      17       0        216

In [132]:
weekly_sales["Total ($)"]=total.T

In [130]:
total.shape,weekly_sales.shape

((1, 5), (5, 3))

In [133]:
weekly_sales

Almond  Peanut  Cachew  Total ($)
Mon       12      19       2        296
Tue        7      12       1        178
Wed        1       6       8        154
Thur      12       0       4        168
Fri        8      17       0        216

### Comparison

In [134]:
ar1 == ar2

array([[ True,  True, False,  True],
       [False, False, False, False]])

### Sort

In [136]:
random_ar=np.random.randint(10,size=(4,4))

In [137]:
random_ar

array([[6, 1, 4, 5],
       [7, 1, 1, 4],
       [1, 2, 3, 6],
       [3, 3, 7, 4]])

In [139]:
np.sort(random_ar)

array([[1, 4, 5, 6],
       [1, 1, 4, 7],
       [1, 2, 3, 6],
       [3, 3, 4, 7]])

In [141]:
np.argsort(random_ar)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [144]:
np.argmin(random_ar,axis=0)

array([0, 1, 2, 0], dtype=int64)

In [145]:
np.argmax(random_ar,axis=0)

array([3, 0, 0, 1], dtype=int64)

In [146]:
np.max(random_ar)

7

In [151]:
from matplotlib.image import imread
panda = imread("panda.png")
type(panda)


numpy.ndarray

In [152]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0